sonar.projectKey=DinoSaulo_Quick-WhatsApp-Contact
sonar.organization=dinosaulo

sonar.sources=src,scripts
sonar.tests=tests
sonar.exclusions=dist/**,node_modules/**,reports/**
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info
